<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-22T15:02:13 BRT" name="Default suite" finished-at="2025-01-22T15:02:26 BRT" duration-ms="13439">
    <groups>
    </groups>
    <test started-at="2025-01-22T15:02:13 BRT" name="Default test" finished-at="2025-01-22T15:02:26 BRT" duration-ms="13439">
      <class name="testsFront.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:13 BRT" name="setup" finished-at="2025-01-22T15:02:16 BRT" duration-ms="3121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testEmailBlankError()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:16 BRT" name="testEmailBlankError" finished-at="2025-01-22T15:02:16 BRT" duration-ms="524" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEmailBlankError -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:16 BRT" name="teardown" finished-at="2025-01-22T15:02:17 BRT" duration-ms="299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:17 BRT" name="setup" finished-at="2025-01-22T15:02:19 BRT" duration-ms="2104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testInvalidCredentialsError()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:19 BRT" name="testInvalidCredentialsError" finished-at="2025-01-22T15:02:19 BRT" duration-ms="569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidCredentialsError -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:19 BRT" name="teardown" finished-at="2025-01-22T15:02:20 BRT" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:20 BRT" name="setup" finished-at="2025-01-22T15:02:22 BRT" duration-ms="2387" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testPasswordBlankError()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:22 BRT" name="testPasswordBlankError" finished-at="2025-01-22T15:02:22 BRT" duration-ms="445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPasswordBlankError -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:22 BRT" name="teardown" finished-at="2025-01-22T15:02:23 BRT" duration-ms="509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:23 BRT" name="setup" finished-at="2025-01-22T15:02:25 BRT" duration-ms="2163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testValidLogin()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:25 BRT" name="testValidLogin" finished-at="2025-01-22T15:02:26 BRT" duration-ms="595" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[O texto da mensagem de nível de acesso está incorreto. expected [Products1] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: O texto da mensagem de nível de acesso está incorreto. expected [Products1] but found [Products]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testsFront.LoginTest.testValidLogin(LoginTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testsFront.LoginTest@6c284af]" started-at="2025-01-22T15:02:26 BRT" name="teardown" finished-at="2025-01-22T15:02:26 BRT" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testsFront.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
